import { Layout } from "../components/MainLayout";
import type { NextPage } from "next";
import Head from "next/head";
import {
  Grid,
  Collapse,
  Card,
  Text,
  Avatar,
  Link,
  Container,
  Row,
} from "@nextui-org/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout></Layout>
    </>
  );
};

export default Home;
